name: reminder_app
description: "A task scheduling and reminder app."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  state_view: ^0.1.2
  toastification: ^3.0.2
  # UI Components
  easy_date_timeline: ^2.0.9

  # State Management
  provider: ^6.1.1
  freezed_annotation: ^3.0.0
  # Navigation
  go_router: ^15.1.2
  # Authentication
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3

  # Storage
  cloud_firestore: ^5.6.7
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4
  loading_animation_widget: ^1.3.0
  action_slider: ^0.7.0
  flutter_otp_text_field: ^1.5.1+1
  table_calendar: ^3.0.9
  curved_navigation_bar: ^1.0.6
  lucide_icons: ^0.257.0
  timeago: ^3.7.0
  flutter_local_notifications: ^19.2.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^3.0.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Sora
      fonts:
        - asset: fonts/Sora-ExtraBold.ttf
          weight: 800
        - asset: fonts/Sora-Bold.ttf
          weight: 700
        - asset: fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: fonts/Sora-Medium.ttf
          weight: 500
        - asset: fonts/Sora-Regular.ttf
          weight: 400
        - asset: fonts/Sora-Light.ttf
          weight: 300
        - asset: fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: fonts/Sora-Thin.ttf
          weight: 100

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
